### ISSUE TITLE
Running Istanbul changes number of tests that are executed

### ISSUE THREAD

**Issue by itsjamie** [JS-DevTools/coverage-istanbul-loader#1]
Hello!

We're running tests in Karma, and while on master we're using istanbul-instrumenter-loader normally, I tested your package to see if it fixed our issue since you've upgraded to the newer APIs, but it was still demonstrating the issue.

We noticed that while running tests through karma-webpack, and using this package to get coverage numbers, the number of tests that are run changes between runs.

I tested removing this package and all unit tests are run every time, and I cannot reproduce the issue, so it seems that running this module is causing our setup to act oddly.

Any ideas as to what might be happening?

Our issue tracking this: https://github.com/video-dev/hls.js/issues/2125

**Comment by JamesMessinger** [comment]
Very odd.  I've never seen that behavior before.  I think the best thing to do is create a minimal reproduction of the issue, so we can more easily hone in on the root cause.  

I'd suggest that you create a new GitHub repo from scratch and slowly start adding as little code as possible and as few libraries as possible until you're able to reproduce the bug.  Then start removing things one at a time to see which thing changes the behavior.  Once you've nailed it down, you can link me to the repo and I'll take a look.

**Comment by itsjamie** [comment]
Hey James, upgrading to Karma 3.1.4 and switching seems to have resolved our issue.

Thank you.

**Comment by JamesMessinger** [comment]
Awesome! Great to hear!
